export let limitData = [
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Financial Products",
            "Risk Taker Name": "IBL Treasury Financial Products",
            "Facility Id": "103851",
            "Facility Type": "P",
            "Limit Id": "2094688",
            "Limit Type": "BS",
            "Product": "CDS CPY RISK",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Financial Products",
            "Risk Taker Name": "IBL Treasury Financial Products",
            "Facility Id": "629348",
            "Facility Type": "P",
            "Limit Id": "4004926",
            "Limit Type": "BS",
            "Product": "BOND DVP",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "1000000",
            "Total Approved Limit": "1000000"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103846",
            "Facility Type": "P",
            "Limit Id": "1992252",
            "Limit Type": "BS",
            "Product": "BASE",
            "Risk Type": "SR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "30000000",
            "Total Approved Limit": "30000000"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103846",
            "Facility Type": "P",
            "Limit Id": "1992253",
            "Limit Type": "BS",
            "Product": "BASE",
            "Risk Type": "ELR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103846",
            "Facility Type": "P",
            "Limit Id": "2079190",
            "Limit Type": "BS",
            "Product": "BASE",
            "Risk Type": "TENOR",
            "Currency": "MTH",
            "Exposure Amount": "0",
            "Total Current Limit": "12",
            "Total Approved Limit": "12"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103846",
            "Facility Type": "P",
            "Limit Id": "2265157",
            "Limit Type": "BS",
            "Product": "BASE",
            "Risk Type": "NR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "75000000",
            "Total Approved Limit": "75000000"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103847",
            "Facility Type": "P",
            "Limit Id": "1984097",
            "Limit Type": "BS",
            "Product": "BOND BSBACK",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "4500000",
            "Total Current Limit": "199000000",
            "Total Approved Limit": "199000000"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103851",
            "Facility Type": "P",
            "Limit Id": "57878828",
            "Limit Type": "BS",
            "Product": "CDS CPY RISK",
            "Risk Type": "NR",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "50000000",
            "Total Approved Limit": "50000000"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103851",
            "Facility Type": "P",
            "Limit Id": "57878829",
            "Limit Type": "BS",
            "Product": "CDS CPY RISK",
            "Risk Type": "TENOR",
            "Currency": "YRS",
            "Exposure Amount": "0",
            "Total Current Limit": "6",
            "Total Approved Limit": "6"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103852",
            "Facility Type": "P",
            "Limit Id": "2000412",
            "Limit Type": "BS",
            "Product": "CSA",
            "Risk Type": "THRESHOLD",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "1",
            "Total Approved Limit": "1"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103853",
            "Facility Type": "P",
            "Limit Id": "1984099",
            "Limit Type": "BS",
            "Product": "EQUITY",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103853",
            "Facility Type": "P",
            "Limit Id": "2048753",
            "Limit Type": "BS",
            "Product": "EQUITY",
            "Risk Type": "PREMIUM",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103854",
            "Facility Type": "P",
            "Limit Id": "1988138",
            "Limit Type": "BS",
            "Product": "FOREX",
            "Risk Type": "SR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "100000000",
            "Total Approved Limit": "100000000"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103854",
            "Facility Type": "P",
            "Limit Id": "1992256",
            "Limit Type": "BS",
            "Product": "FOREX",
            "Risk Type": "ELR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103854",
            "Facility Type": "P",
            "Limit Id": "2048754",
            "Limit Type": "BS",
            "Product": "FOREX",
            "Risk Type": "NR",
            "Currency": "USD",
            "Exposure Amount": "139593699",
            "Total Current Limit": "350900000",
            "Total Approved Limit": "350900000"
        },
        {
            "Entity Id": "18197044",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103854",
            "Facility Type": "P",
            "Limit Id": "48618622",
            "Limit Type": "BS",
            "Product": "FOREX",
            "Risk Type": "TENOR",
            "Currency": "YRS",
            "Exposure Amount": "0",
            "Total Current Limit": "2",
            "Total Approved Limit": "2"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103855",
            "Facility Type": "P",
            "Limit Id": "1992257",
            "Limit Type": "BS",
            "Product": "FOREX DERIV",
            "Risk Type": "ELR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103855",
            "Facility Type": "P",
            "Limit Id": "48618620",
            "Limit Type": "BS",
            "Product": "FOREX DERIV",
            "Risk Type": "NR",
            "Currency": "USD",
            "Exposure Amount": "32496301",
            "Total Current Limit": "17500000",
            "Total Approved Limit": "17500000"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103855",
            "Facility Type": "P",
            "Limit Id": "48618621",
            "Limit Type": "BS",
            "Product": "FOREX DERIV",
            "Risk Type": "TENOR",
            "Currency": "YRS",
            "Exposure Amount": "0",
            "Total Current Limit": "10",
            "Total Approved Limit": "10"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103857",
            "Facility Type": "P",
            "Limit Id": "2089180",
            "Limit Type": "BS",
            "Product": "GUARANTEE",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "10000000",
            "Total Approved Limit": "10000000"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103858",
            "Facility Type": "P",
            "Limit Id": "1979948",
            "Limit Type": "BS",
            "Product": "INT TRADE",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103858",
            "Facility Type": "P",
            "Limit Id": "1992259",
            "Limit Type": "BS",
            "Product": "INT TRADE",
            "Risk Type": "PREMIUM",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "4000000",
            "Total Approved Limit": "4000000"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103858",
            "Facility Type": "P",
            "Limit Id": "2265414",
            "Limit Type": "BS",
            "Product": "INT TRADE",
            "Risk Type": "NR",
            "Currency": "ZAR",
            "Exposure Amount": "21252915125",
            "Total Current Limit": "4478600000",
            "Total Approved Limit": "4478600000"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103858",
            "Facility Type": "P",
            "Limit Id": "2265416",
            "Limit Type": "BS",
            "Product": "INT TRADE",
            "Risk Type": "TENOR",
            "Currency": "YRS",
            "Exposure Amount": "0",
            "Total Current Limit": "12",
            "Total Approved Limit": "12"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103859",
            "Facility Type": "P",
            "Limit Id": "1988141",
            "Limit Type": "BS",
            "Product": "PRECIOUS",
            "Risk Type": "SR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "30000000",
            "Total Approved Limit": "30000000"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103859",
            "Facility Type": "P",
            "Limit Id": "1992260",
            "Limit Type": "BS",
            "Product": "PRECIOUS",
            "Risk Type": "ELR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103859",
            "Facility Type": "P",
            "Limit Id": "2265200",
            "Limit Type": "BS",
            "Product": "PRECIOUS",
            "Risk Type": "NR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "150000000",
            "Total Approved Limit": "150000000"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "103859",
            "Facility Type": "P",
            "Limit Id": "48618619",
            "Limit Type": "BS",
            "Product": "PRECIOUS",
            "Risk Type": "TENOR",
            "Currency": "MTH",
            "Exposure Amount": "0",
            "Total Current Limit": "12",
            "Total Approved Limit": "12"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "335849",
            "Facility Type": "P",
            "Limit Id": "2614333",
            "Limit Type": "BS",
            "Product": "BOND BSBACK",
            "Risk Type": "ELR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "337049",
            "Facility Type": "P",
            "Limit Id": "2616463",
            "Limit Type": "BS",
            "Product": "FX_BOND_REPO",
            "Risk Type": "ELR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "11000000",
            "Total Approved Limit": "11000000"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "337049",
            "Facility Type": "P",
            "Limit Id": "2616464",
            "Limit Type": "BS",
            "Product": "FX_BOND_REPO",
            "Risk Type": "NR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "337049",
            "Facility Type": "P",
            "Limit Id": "2616465",
            "Limit Type": "BS",
            "Product": "FX_BOND_REPO",
            "Risk Type": "SR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19004830",
            "Risk Taker Group Name": "ICIB - SA",
            "Risk Taker Name": "IBL Treasury",
            "Facility Id": "750398",
            "Facility Type": "F",
            "Limit Id": "48618312",
            "Limit Type": "ACL",
            "Product": "CBI",
            "Risk Type": "P_PFE",
            "Currency": "ZAR",
            "Exposure Amount": "72139024",
            "Total Current Limit": "202000000",
            "Total Approved Limit": "202000000"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Balance Sheet Funding",
            "Risk Taker Name": "11050 Treasury BSF",
            "Facility Id": "0",
            "Facility Type": "L",
            "Limit Id": "0",
            "Limit Type": "CCL",
            "Product": "LOAN_TERM_BS",
            "Risk Type": "P_ELR_CPY",
            "Currency": "ZAR",
            "Exposure Amount": "2628200000",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Balance Sheet Funding",
            "Risk Taker Name": "IBL Treasury Balance Sheet Funding",
            "Facility Id": "103849",
            "Facility Type": "P",
            "Limit Id": "1988137",
            "Limit Type": "BS",
            "Product": "BOND HELD",
            "Risk Type": "ELR",
            "Currency": "EUR",
            "Exposure Amount": "0",
            "Total Current Limit": "256000000",
            "Total Approved Limit": "256000000"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Balance Sheet Funding",
            "Risk Taker Name": "IBL Treasury Balance Sheet Funding",
            "Facility Id": "103850",
            "Facility Type": "P",
            "Limit Id": "1992255",
            "Limit Type": "BS",
            "Product": "CD",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "1607100000",
            "Total Approved Limit": "1607100000"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Balance Sheet Funding",
            "Risk Taker Name": "IBL Treasury Balance Sheet Funding",
            "Facility Id": "103866",
            "Facility Type": "P",
            "Limit Id": "1992261",
            "Limit Type": "BS",
            "Product": "BSE_LENDING",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "2527623745",
            "Total Current Limit": "6500000000",
            "Total Approved Limit": "6500000000"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Balance Sheet Funding",
            "Risk Taker Name": "IBL Treasury Balance Sheet Funding",
            "Facility Id": "103867",
            "Facility Type": "P",
            "Limit Id": "1988142",
            "Limit Type": "BS",
            "Product": "NBSE_LENDING",
            "Risk Type": "ELR",
            "Currency": "USD",
            "Exposure Amount": "0",
            "Total Current Limit": "15000000",
            "Total Approved Limit": "15000000"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Balance Sheet Funding",
            "Risk Taker Name": "IBL Treasury Balance Sheet Funding",
            "Facility Id": "346509",
            "Facility Type": "P",
            "Limit Id": "2689334",
            "Limit Type": "BS",
            "Product": "BOND HELD",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Scrip Lending",
            "Risk Taker Name": "IBL-TSFSL IBL Treasury Script Lending",
            "Facility Id": "632019",
            "Facility Type": "P",
            "Limit Id": "2004397",
            "Limit Type": "BS",
            "Product": "STOCK LEND",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "421847838.1",
            "Total Current Limit": "500000000",
            "Total Approved Limit": "500000000"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Scrip Lending",
            "Risk Taker Name": "IBL-TSFSL IBL Treasury Script Lending",
            "Facility Id": "632019",
            "Facility Type": "P",
            "Limit Id": "17400469",
            "Limit Type": "BS",
            "Product": "STOCK LEND",
            "Risk Type": "NR",
            "Currency": "ZAR",
            "Exposure Amount": "825813450.7",
            "Total Current Limit": "2500000000",
            "Total Approved Limit": "2500000000"
        },
        {
            "Entity Id": "19515110",
            "Risk Taker Group Name": "ICIB - SA - Interest Rate Trading",
            "Risk Taker Name": "IBL-TSFINT IBL Treasury Interest Rate",
            "Facility Id": "103848",
            "Facility Type": "P",
            "Limit Id": "1984098",
            "Limit Type": "BS",
            "Product": "BOND DVP",
            "Risk Type": "ELR",
            "Currency": "ZAR",
            "Exposure Amount": "35406.49",
            "Total Current Limit": "2000000",
            "Total Approved Limit": "2000000"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDSALES TPD Sales",
            "Facility Id": "645175",
            "Facility Type": "P",
            "Limit Id": "9075090",
            "Limit Type": "BS",
            "Product": "ENERGY",
            "Risk Type": "BOE",
            "Currency": "CHF",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDSALES TPD Sales",
            "Facility Id": "645175",
            "Facility Type": "P",
            "Limit Id": "9075091",
            "Limit Type": "BS",
            "Product": "ENERGY",
            "Risk Type": "ELR",
            "Currency": "CHF",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDSALES TPD Sales",
            "Facility Id": "645175",
            "Facility Type": "P",
            "Limit Id": "9075092",
            "Limit Type": "BS",
            "Product": "ENERGY",
            "Risk Type": "NR",
            "Currency": "CHF",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "10"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDSALES TPD Sales",
            "Facility Id": "645175",
            "Facility Type": "P",
            "Limit Id": "9075093",
            "Limit Type": "BS",
            "Product": "ENERGY",
            "Risk Type": "MTM",
            "Currency": "CHF",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDSALES TPD Sales",
            "Facility Id": "645175",
            "Facility Type": "P",
            "Limit Id": "9075094",
            "Limit Type": "BS",
            "Product": "ENERGY",
            "Risk Type": "TENOR",
            "Currency": "DAY",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDSALES TPD Sales",
            "Facility Id": "645175",
            "Facility Type": "P",
            "Limit Id": "62392467",
            "Limit Type": "BS",
            "Product": "ENERGY",
            "Risk Type": "VAR",
            "Currency": "CHF",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDTRAD TPD Trading",
            "Facility Id": "103864",
            "Facility Type": "P",
            "Limit Id": "1979958",
            "Limit Type": "BS",
            "Product": "ALL FX",
            "Risk Type": "ELR",
            "Currency": "GBP",
            "Exposure Amount": "0",
            "Total Current Limit": "2000000",
            "Total Approved Limit": "2000000"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDTRAD TPD Trading",
            "Facility Id": "103864",
            "Facility Type": "P",
            "Limit Id": "1988146",
            "Limit Type": "BS",
            "Product": "ALL FX",
            "Risk Type": "SR",
            "Currency": "GBP",
            "Exposure Amount": "0",
            "Total Current Limit": "20000000",
            "Total Approved Limit": "20000000"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDTRAD TPD Trading",
            "Facility Id": "103864",
            "Facility Type": "P",
            "Limit Id": "2000415",
            "Limit Type": "BS",
            "Product": "ALL FX",
            "Risk Type": "BOE",
            "Currency": "GBP",
            "Exposure Amount": "0",
            "Total Current Limit": "2000000",
            "Total Approved Limit": "2000000"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDTRAD TPD Trading",
            "Facility Id": "103864",
            "Facility Type": "P",
            "Limit Id": "2000416",
            "Limit Type": "BS",
            "Product": "ALL FX",
            "Risk Type": "NR",
            "Currency": "GBP",
            "Exposure Amount": "0",
            "Total Current Limit": "20000000",
            "Total Approved Limit": "20000000"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDTRAD TPD Trading",
            "Facility Id": "103864",
            "Facility Type": "P",
            "Limit Id": "2048781",
            "Limit Type": "BS",
            "Product": "ALL FX",
            "Risk Type": "MTM",
            "Currency": "GBP",
            "Exposure Amount": "0",
            "Total Current Limit": "0",
            "Total Approved Limit": "0"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDTRAD TPD Trading",
            "Facility Id": "103864",
            "Facility Type": "P",
            "Limit Id": "2079188",
            "Limit Type": "BS",
            "Product": "ALL FX",
            "Risk Type": "TENOR",
            "Currency": "DAY",
            "Exposure Amount": "0",
            "Total Current Limit": "2",
            "Total Approved Limit": "2"
        },
        {
            "Entity Id": "20152544",
            "Risk Taker Group Name": "Corporate Institutional Banking Group",
            "Risk Taker Name": "LTPDTRAD TPD Trading",
            "Facility Id": "103864",
            "Facility Type": "P",
            "Limit Id": "2209165",
            "Limit Type": "BS",
            "Product": "ALL FX",
            "Risk Type": "VAR",
            "Currency": "GBP",
            "Exposure Amount": "0",
            "Total Current Limit": "2000000",
            "Total Approved Limit": "2000000"
        }
    
]